const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const assert = require('node:assert/strict');
const path = require('node:path');
(async () => {
  const server = spawn(process.execPath,[path.join(__dirname,'../serve.cjs')]);
  let browser;
  try {
    await new Promise(resolve => server.stdout.once('data',resolve));
    browser = await chromium.launch({headless:true,channel:'msedge'});
    const context = await browser.newContext({viewport:{width:390,height:844}});
    const page = await context.newPage();
    const errors=[];
    page.on('pageerror',error=>errors.push(error.message));
    await page.goto('http://localhost:3456');
    await page.evaluate(async () => { await navigator.serviceWorker.ready; });
    await page.reload();
    for(const [group,value] of Object.entries({rodilla:'bien',energia:'bien',comida:'comido',tiempo:'60'})) await page.locator(`[data-group="${group}"][data-value="${value}"]`).click();
    await page.locator('#btn-next-checkin').click();
    await page.waitForSelector('.sess-card');
    await page.evaluate(()=>selectSession('push'));
    await page.locator('.as-add-btn').click();
    await page.reload();
    await page.waitForSelector('#screen-active:not(.hidden)');
    assert.equal(await page.evaluate(()=>state.sessionSets.press_inclinado.length),1);
    await page.evaluate(()=>finishSession());
    await page.locator('#notes-textarea').fill('Prueba persistente');
    await page.locator('.notes-save-btn').first().click();
    await page.waitForSelector('#screen-history:not(.hidden)');
    assert.equal(await page.evaluate(async ()=>(await getAllSessions()).length),1);
    assert.ok((await page.locator('#history-content').innerText()).includes('Prueba persistente'));
    await context.setOffline(true);
    await page.reload();
    await page.waitForSelector('#screen-checkin:not(.hidden)');
    await page.evaluate(()=>showHistory());
    await page.waitForSelector('#screen-history:not(.hidden)');
    assert.equal(await page.evaluate(async ()=>(await getAllSessions()).length),1);
    await page.evaluate(()=>openChat());
    await page.locator('#chat-input').fill('última sesión');
    await page.locator('#chat-send-btn').click();
    await page.waitForFunction(()=>document.getElementById('chat-messages').textContent.includes('Tu última sesión fue'));
    assert.deepEqual(errors,[]);
    await page.evaluate(()=>{closeChat();initCheckin();});
    for(const [group,value] of Object.entries({rodilla:'bien',energia:'mareo',comida:'comido',tiempo:'60'})) await page.locator(`[data-group="${group}"][data-value="${value}"]`).click();
    await page.locator('#btn-next-checkin').click();
    await page.waitForSelector('#screen-warnings:not(.hidden)');
    assert.ok((await page.locator('#warnings-list').innerText()).includes('Mareo'));
    await page.evaluate(()=>selectSession('push'));
    assert.equal(await page.locator('#screen-active').isVisible(),false);
    await page.evaluate(()=>{startRestTimer(1);});
    await page.waitForFunction(()=>state.restRemaining===0);
    assert.equal(await page.locator('#rest-countdown').innerText(),'0:00');
    console.log('PASS: mobile flow, draft recovery, IndexedDB persistence, offline reload and local coach');
  } finally { if(browser) await browser.close(); server.kill(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
